### ISSUE TITLE
feature request: `expand()`/ `collapse()` should also resize window

### ISSUE THREAD

**Issue by chrisgrieser** [stevearc/quicker.nvim#10]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

when using `expand()` or `collapse()`, also adjust the window size.

### Provide background

Right now, using `expand()` does not affect window size. That means, if I have for example 5 items in my qflist, after expanding, the window is still 5 lines high, which is somewhat too small to properly work with.

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
I agree with the sizing, but this is such a simple thing to do with your own bindings that I don't think it's worth complicating the API that quicker provides. This is what I do in my own config:

```lua
function()
  require("quicker").expand({ before = 2, after = 2, add_to_existing = true })
  vim.api.nvim_win_set_height(0, math.min(20, vim.api.nvim_buf_line_count(0)))
end
```
