### ISSUE TITLE
feature request: highlight treesitter off if the quickfix list is long.

### ISSUE THREAD

**Issue by sergiornelas** [stevearc/quicker.nvim#12]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Hello. I love your plugin btw. But if I get the LSP references and the list is quite big (+100 references), the quickfix renders slower. Maybe we could add an option that disables the treesitter highlight if the list is 50+ elements.
:-)

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
Could you be a bit more specific about the problem you are seeing? Does the quickfix buffer take longer to open? Is it causing Neovim to be laggy? Is it just taking a while to highlight?

I made the highlighting (both treesitter and LSP) async with the intention that highlighting might take longer for long lists, but it _shouldn't_ block the UI and ideally won't add much lag (some lag is unavoidable).

**Comment by stevearc** [comment]
closing for lack of response
