### ISSUE TITLE
feature request: Add the Number of Files Changed to the Notification

### ISSUE THREAD

**Issue by bassamsdata** [stevearc/quicker.nvim#13]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Thank you for this amazing plugin. This might be nitpicking, but I'd like to suggest adding a notification that says something like `applied 5 changes in 3 files`. I think this would be very useful.

### Provide background

Currently, I have this implemented for LSP renaming, with the number of files changed shown in a notification like the one below, which is a modified module.

<img width="437" alt="Screenshot 2024-08-10 at 11 08 32 AM" src="https://github.com/user-attachments/assets/d479f6c5-2b16-444f-a742-a70478ed2c98">

Thanks again for the plugin!

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
Done!

**Comment by bassamsdata** [comment]
Thank you, it works like a charm!
