### ISSUE TITLE
feature request: Display current line for `vim.diagnostic`

### ISSUE THREAD

**Issue by stevalkr** [stevearc/quicker.nvim#16]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

When using `vim.diagnostic.setloclist` or `vim.diagnostic.setqflist`, the message in quickfix is not the content of that line. Expanding it results in

```cpp
void example() {
Use of undeclared identifier 'x'
}
```

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
I've added some logic to better handle these cases. See if it does what you want!
