### ISSUE TITLE
How to bind the cursorline to the current item in quickfix list like in the videos

### ISSUE THREAD

**Issue by 231tr0n** [stevearc/quicker.nvim#23]
Hi stevearc!! Thank you for this amazing plugin. I was trying it out and found few things out which I wanted to clarify about:-

1. Moving cursor inside the quickfix does not move the current selected item of the quickfix list along with it like it does in your demo. What do you think I might be doing wrong here for it to not happen? ![image](https://github.com/user-attachments/assets/75cb5bb7-6447-40a0-9090-51874f1c2bd0)
2. In the same picture above, first level indentations are given only 1 space rather than 2 even though my tabstop is 2. Is it possible for all the lines to be of same indentation.

**Comment by serranomorante** [comment]
Hi! about cursorline, I have this in `nvim/syntax/qf.vim`. It might help:

```vim
if exists('b:current_syntax')
    finish
endif

setlocal cursorline
setlocal cursorlineopt=line

let b:current_syntax = 'qf'
```

**Comment by 231tr0n** [comment]
> Hi! about cursorline, I have this in `nvim/syntax/qf.vim`. It might help:
> 
> ```viml
> if exists('b:current_syntax')
>     finish
> endif
> 
> setlocal cursorline
> setlocal cursorlineopt=line
> 
> let b:current_syntax = 'qf'
> ```
> 
> If you have `syntax off` you might need to enable syntax for qf filetypes.

Hi! Thank you for responding. Let me check if it works.

**Comment by 231tr0n** [comment]
> Hi! about cursorline, I have this in `nvim/syntax/qf.vim`. It might help:
> 
> ```viml
> if exists('b:current_syntax')
>     finish
> endif
> 
> setlocal cursorline
> setlocal cursorlineopt=line
> 
> let b:current_syntax = 'qf'
> ```
> 
> If you have `syntax off` you might need to enable syntax for qf filetypes.

@serranomorante apparantly it does not work as it was in the videos with the options you provided. I read the help file for the options which you suggested and I think it changes how cursorline highlighting works ig. But I dont think it will bind the cursor to the current quickfix item afaik.

**Comment by serranomorante** [comment]
The snippet I provided will add a highlight to your cursor as you navigate (to better identify the highlighted row), but it don't actually **selects** any quickfix item. You mean moving the cursor should also change the selected buffer (outside the quickfix list) live?

[qf-cursorline-2024-09-08_19.11.26.webm](https://github.com/user-attachments/assets/fdb63b5e-11dd-413a-9382-21ee41be0402)

**Comment by 231tr0n** [comment]
> The snippet I provided will add a highlight to your cursor as you navigate (to better identify the highlighted row), but it don't actually **selects** any quickfix item. You mean moving the cursor should also change the selected buffer (outside the quickfix list) live?
> qf-cursorline-2024-09-08_19.11.26.webm

No I meant moving the cursor should change the selected item in the quickfix list along with it as shown in the video

**Comment by stevearc** [comment]
In the video I was actually using my old quickfix plugin for having the cursor follow along. That plugin was a little janky, not very featureful, and is deprecated now. For a while quicker.nvim did not have the feature to scroll the quickfix window to the closest item, but I have just added it! Set `follow.enabled = true` when you call `setup()`.

As for the indentation, I've also recently provided some more configuration via the `trim_leading_whitespace` option. You can opt for conform to remove all the leading whitespace, none of it, or only the amount of leading whitespace shared among all the results from the same file (the default option).

**Comment by rbhanot4739** [comment]
@stevearc Sorry to comment on a closed issue, but I am not quite clear how `follow.enable` is supposed to behave. I have the following in my config and but it doesn't seem to do anything. 
```
opts = {
      follow = {
        enabled = true,
      },
    }
```

**Comment by stevearc** [comment]
When the quickfix window is open, as you navigate around other buffers the quickfix list will automatically scroll to whichever item is the closest to your current cursor position. Note that your position in the qflist will be unchanged (e.g. `cnext`/`cprev` will go in the same order), it's just the cursor position that will be updated.

**Comment by stevearc** [comment]
@rbhanot4739 yes, if that is not working please file a bug report with a repro.
There is one caveat: this only works if the results in the quickfix are sorted
https://github.com/stevearc/quicker.nvim/blob/1798be71cdcb15fb84fa8054148a56e17fd391dc/lua/quicker/follow.lua#L44-L50
So first check if that is the case, because that is the most likely culprit.
