### ISSUE TITLE
bug: Quickfix entries unintentionally truncated

### ISSUE THREAD

**Issue by rliebz** [stevearc/quicker.nvim#26]
### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1724512491

### Operating system/version

MacOS 14.6.1

### Describe the bug

Part of the quickfix text may be excluded from the list, and when saving, deleted from the buffer.

### What is the severity of this bug?

breaking (some functionality is broken)

### Steps To Reproduce

1. `nvim -u repro.lua .` in the directory with the example file
2. `:Telescope live_grep`. Not sure if the problem is telescope-specific, but this is typically how I open a quickfix window. 
3. Type the word: `foo`. You should see 2 entries
4. Press `ctrl`+`q` to move the items to the quickfix window
5. Notice that the quickfix window truncates the beginning of the first entry:
```
example.txt ┃ 1┃oo
example.txt ┃ 2┃foo
```
6. Make an edit to line 2. For example, change `foo` to `foobar`.
7. Save the quickfix window.
8. Notice that the original file has been modified where the `f` is removed in line 1, and the word is preceded by 3 tabs instead of two spaces, despite only modifying line 2:
```
			oo
			foobar
```

### Expected Behavior

The quickfix window should resemble the default, where each word is legible:
```
example.txt|1 col 3| foo
example.txt|2 col 4| foo
```

The edit should only affect the second line:
```
  foo
			foobar
```

### Minimal example file

It is important that the first line begins with 2 spaces, and the second line begins with 3 tabs:

```
  foo
			foo
```

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	{
		"stevearc/quicker.nvim",
		config = function()
			require("quicker").setup({
				-- add your config here
			})
		end,
	},
	{
		"nvim-telescope/telescope.nvim",
		dependencies = {
			{ "nvim-lua/plenary.nvim" },
		},
		opts = {},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

I have only managed to reproduce this when mixing tabs and spaces. Changing `tabstop` does not appear to change the behavior at all.

**Comment by stevearc** [comment]
I believe this was an issue with `trim_leading_whitespace`. I've committed a change; can you check to see if this fixes the issue for you?

**Comment by rliebz** [comment]
Appreciate you following up here!

This does stop it from cutting off characters and allows edits. It unfortunately does still have variable leading indentation, although it no longer seems to sometimes cut off the first non-whitespace character. For example:

```
runner/option_test.go ┃ 17┃{When: WhenList{whenFalse}, Value: "foo"},
runner/option_test.go ┃ 18┃{When: WhenList{createWhen(
runner/option_test.go ┃ 22┃{When: WhenList{createWhen(
runner/option_test.go ┃ 82┃		{When: WhenList{whenFalse}, Value: "foo"},
runner/option_test.go ┃ 83┃		{When: WhenList{whenTrue}, Value: "bar"},
runner/option_test.go ┃ 84┃		{When: WhenList{whenFalse}, Value: "baz"},
runner/option_test.go ┃ 93┃			{When: WhenList{whenTrue}, Value: "when"},
runner/option_test.go ┃135┃	{When: WhenList{whenFalse}, Value: "wrong"},
runner/option_test.go ┃137┃		When:  WhenList{createWhen(withWhenEqual("foo", "foovalue"))},
runner/option_test.go ┃140┃	{When: WhenList{whenFalse}, Value: "oops"},
```

Compared to the builtin, which consistently uses 1 space regardless of leading indentation in the source file:
```
runner/option_test.go|17 col 4| {When: WhenList{whenFalse}, Value: "foo"},
runner/option_test.go|18 col 4| {When: WhenList{createWhen(
runner/option_test.go|22 col 4| {When: WhenList{createWhen(
runner/option_test.go|82 col 6| {When: WhenList{whenFalse}, Value: "foo"},
runner/option_test.go|83 col 6| {When: WhenList{whenTrue}, Value: "bar"},
runner/option_test.go|84 col 6| {When: WhenList{whenFalse}, Value: "baz"},
runner/option_test.go|93 col 7| {When: WhenList{whenTrue}, Value: "when"},
runner/option_test.go|135 col 5| {When: WhenList{whenFalse}, Value: "wrong"},
runner/option_test.go|137 col 5| When:  WhenList{createWhen(withWhenEqual("foo", "foovalue"))},
runner/option_test.go|140 col 5| {When: WhenList{whenFalse}, Value: "oops"},
```

Here's the file I pulled that from, with a Telescope query of `When:` (this was the original file where I noticed an issue, but figured I'd lead with a smaller repro): https://github.com/rliebz/tusk/blob/de4f01cb531f5a95bbc6545dda61c371230e3d8d/runner/option_test.go

**Comment by stevearc** [comment]
Ah, there are three possible ways to handle whitespace:
1. Show all of it - upside: easy to do. downside: harder to visually parse
2. Trim off the common leading whitespace - upside: mix of easier to visually parse while preserving indentation relationship. downside: more complex; fails with mixed leading whitespace
3. Trim off _all_ whitespace - upside: easy to do. downside: can't see relative indentation differences between lines; can't change the indentation of a line.

We currently support only 1 & 2. The builtin method is 3. I would argue that 2 is optimal in 95% of cases, but as you have found with mixed leading whitespace 3 might be preferable to 1. I'll leave this issue open as a placeholder for changing the current `trim_leading_whitespace` option from a boolean to an enum that supports method 3.

**Comment by rliebz** [comment]
Thanks for following up!

Unfortunately it looks like this messes with the syntax highlighting. 

With default settings:
<img width="686" alt="image" src="https://github.com/user-attachments/assets/07b5c91d-f4dd-4632-8e84-07a1c7b06af3" />

With "all":
<img width="676" alt="image" src="https://github.com/user-attachments/assets/8f7043d9-65b4-4464-ad45-9075cfc52be4" />

This particular example uses treesitter and Go. Let me know if you'd prefer me to open a new issue

**Comment by stevearc** [comment]
Whoops, must have regressed with all the virtual text refactors I did. Should be fixed now!

**Comment by rliebz** [comment]
Looks perfect, thanks!
