### ISSUE TITLE
feature request: jump to previous or next entry when the context is expanded

### ISSUE THREAD

**Issue by TymekDev** [stevearc/quicker.nvim#3]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I think that either a function or a recipe for jumping to the previous or the next entry when the context is expanded would be useful!

### Provide background

I came up with these entries for `keys` (`<` and `>` are the keybinds suggested in the READM). These work, but definitely feel hacky. Perhaps an out-of the box solution would be better?
```lua
 {
  "]q",
  function()
    vim.cmd.normal("<j")
    vim.cmd.normal(">")
  end,
},
{
  "[q",
  function()
    vim.cmd.normal("<k")
    vim.cmd.normal(">")
  end,
},
```
Note: it's deliberately split into two calls, because `vim.cmd.normal("<j>")` stopped at `j` when I had the cursor on the last row.

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
Usually I would use `:cnext` and `:cprev` for this, but that also jumps to those locations. If you just want to move the cursor in the quickfix window, try this:

```lua
require("quicker").setup({
  keys = {
    {
      "]q",
      function()
        local items = vim.fn.getqflist()
        local lnum = vim.api.nvim_win_get_cursor(0)[1]
        for i = lnum + 1, #items do
          if items[i].valid == 1 then
            vim.api.nvim_win_set_cursor(0, { i, 0 })
            return
          end
        end
      end,
    },
    {
      "[q",
      function()
        local items = vim.fn.getqflist()
        local lnum = vim.api.nvim_win_get_cursor(0)[1]
        for i = lnum - 1, 1, -1 do
          if items[i].valid == 1 then
            vim.api.nvim_win_set_cursor(0, { i, 0 })
            return
          end
        end
      end,
    },
  },
})
```

**Comment by TymekDev** [comment]
Thanks! That's definitely cleaner than what I came up with.

I am well aware of `:cnext` and `:cprev` - I even have [nifty mappings](https://github.com/TymekDev/dotfiles/blob/503002805decaf31135d69b9d6dc254ac78c5534/config/nvim/lua/tymek/mappings.lua#L38-L51) to make them wrap at the ends. As you said, though, these jump to locations. With context I can find the right entry and go directly there instead of jumping between locations to find the right one.

Thanks for help and an awesome plugin! 😁
