### ISSUE TITLE
Tabs are gigantic when expanding context

### ISSUE THREAD

**Issue by Axlefublr** [stevearc/quicker.nvim#9]
From the qflist, when I expand context to view my code, shiftwidth is set to some ridiculous value, for example `23` and `27`.
I assume it's because they are used internally by this plugin for some sort of aligning, but since I use tabs for indenting my code, this ends up looking ridiculous.
![image](https://github.com/user-attachments/assets/1bc9fdc7-b26f-4463-8178-26aae2e9a6aa)

**Comment by Axlefublr** [comment]
I tried setting `shiftwidth` in the `opts` table of `opts`, but it doesn't work. Probably because `opts.opts` is for window specific options, and shiftwidth is buffer-local?

**Comment by Axlefublr** [comment]
And while I'm here: thank you SO MUCH for this plugin, I absolutely love it!
I love the qflist, but the default view is just lowkey unusable, so I used other ways to work with it.
Thanks to this plugin, I can finally interact with it a bit richer, which I massively appreciate!

**Comment by Axlefublr** [comment]
I also massively appreciate that you added the lazydev.nvim type to the suggested installation with lazy; having to go through source code to find that type (which I often do) to get suggestions is kinda annoying, so presenting it front and center like that is really thoughtful :3

**Comment by Axlefublr** [comment]
I should maybe open another issue for this, and please tell me if I should, but here's another array of errors, when I tried doing `:vim ;feedkeys_int; **`, to search in every file in cwd:
![image](https://github.com/user-attachments/assets/088bdf36-9421-4b03-b3b3-4c5ecc6e0546)

**Comment by Axlefublr** [comment]
it does end up working, fwiw, just throws a bunch of errors. Seems similar to #8 in that it's throwing errors unnecessarily

**Comment by stevearc** [comment]
Whoah, that's crazy. I'm not doing anything with `shiftwidth` in this plugin, so I suspect it's coming from somewhere else. Could you try starting Neovim in verbose mode with `nvim -V1`, perform the actions to get to the weird quickfix, and then run `:verbose set shiftwidth?`

This should show us exactly where the shiftwidth was last set.

FWIW the `opts` table should [transparently handle](https://github.com/stevearc/quicker.nvim/blob/master/lua/quicker/opts.lua) both buffer and window options. It's possible there's a bug, but the intent at least is for it to work.

**Comment by Axlefublr** [comment]
Thank you! Using `-V1` helped figure out the issue, and I feel like it's not going to be your responsibility to fix it (I'll look into it later)
So the way I got to it:
1. open some file
2. `:vim ;pattern; %` where `pattern` is on a line indented with tabs
3. open qflist through the plugin
4. `expand`
5. `collapse`
Blammo, tabs are ginormous
From `:verbose set shiftwidth?` I realized that it's guess-indent guessindenting where it's not supposed to:
```
:verbose set shiftwidth?
  shiftwidth=15
        Last set from ~/.local/share/nvim/lazy/guess-indent.nvim/lua/guess-indent/init.lua line 101
```

**Comment by stevearc** [comment]
I actually don't know where those notifications are coming from. I grepped the Neovim source for that message and didn't find anything. Actually, [searching all of github](https://github.com/search?q=%22is+not+attached%5C%22%22+language%3ALua+&type=code) didn't turn up a match.

**Comment by Axlefublr** [comment]
`LSP Client with id 1 not attached to buffer 174`, more specifically, sorry. And the `174` number changes for every notification

**Comment by Axlefublr** [comment]
Not sure why I haven't tried this before, but I disabled the quicker plugin and the lsp errors still happened. So, not this plugin's responsibility
